name: Huawei Solar Modbus to MQTT
version: '0.9.0-beta'
slug: huawei_solar_modbus_mqtt
description: Query Huawei Solar Inverter via Modbus and publish to MQTT with auto-discovery (BETA)
url: https://github.com/arboeh/homeassistant-huawei-solar-addon
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
hassio_api: true
hassio_role: default
homeassistant_api: false
host_network: true
services:
  - mqtt:need
options:
  modbus_host: '192.168.1.100'
  modbus_port: 502
  modbus_device_id: 1
  mqtt_topic: 'huawei-solar'
  debug: false
  status_timeout: 180
  poll_interval: 60
schema:
  modbus_host: str
  modbus_port: port
  modbus_device_id: int
  mqtt_host: str?
  mqtt_port: port?
  mqtt_user: str?
  mqtt_password: password?
  mqtt_topic: str
  debug: bool
  status_timeout: int
  poll_interval: int
