name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: 'homeassistant-huawei-solar-addon'
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"docs","section":"Documentation","hidden":false}]'
          # Wenn du PRs komplett vermeiden willst, zus√§tzlich:
          # skip-github-pull-request: true

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Update config.yaml version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          sed -i 's/version: .*/version: ${{ steps.release.outputs.tag_name }}/' huawei-solar-modbus-mqtt/config.yaml
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add huawei-solar-modbus-mqtt/config.yaml
          git commit -m "chore: update version to ${{ steps.release.outputs.tag_name }}"
          git push
